name: Update README

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 4 * * *'   # 04:00 UTC
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update README.md
        run: |
          echo "### Updated at $(date -u)" > README.md

      - name: Commit and push if changed
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update README [auto]"
          git push
